languageCode = "en-esp"
title = "Introductory Course with MicroPython "
theme = "book"

# Needed for mermaid/katex shortcodes
[markup]
    [markup.goldmark.renderer]
        unsafe = true

    [markup.tableOfContents]
        startLevel = 1

BookSearch = true